- src/pf/anf.lua
- src/pf/backend.lua
- src/pf/expand.lua
- src/pf/optimize.lua
- tests/pfquickcheck/pflang_math.lua
* src/pf/anf.lua:
* src/pf/backend.lua:
* src/pf/optimize.lua:
* src/pf/expand.lua: Add *64 op, for 64-bit multiplication.  The
expander will produce this op for all multiplications, and the
optimizer may later reduce it to '*'.
* tests/pfquickcheck/pflang_math.lua: Update to work on the full range
of numbers.
> Proper truncating 32-bit multiplication

- src/pf/optimize.lua
* src/pf/optimize.lua: 64-bit multiplication includes the truncation
operation so we can't just take the min and max of the extrema;
instead return a uint32 range.
> Fix range computation for *64

- src/pf/optimize.lua
This reverts commit 139e919ac024eb311a3f1c2362ab931dd4f9db89.
Table keys can be any object type in Lua.  I was confused by
JavaScript's semantic treatment of all keys as strings.
> Revert "Fix memoization bug"

- src/pf/quickcheck.lua
- src/pf/utils.lua
- tests/Makefile
- tests/pfquickcheck/pflua_ir.lua
- tests/properties/repeatable_randomization.lua
* src/pf/quickcheck.lua: Use utils.equals to check equality, and pp to
print, by default.
* src/pf/utils.lua: Add ability to print arrays whose head is not a
string, and a place to put a full table pretty-printer.
* tests/properties/repeatable_randomization.lua: New test, that our
randomized IR structures can be repeatably generated.
* tests/Makefile: Add new test.
> Test quickcheck's ability to make reproducible randomness

- src/pf/optimize.lua
* src/pf/optimize.lua (infer_ranges): Fix passthrough range propagation
for uint32.  It was off by one!  Fixes #120.
> Fix range inference for uint32 operator

- tools/pflua-optimize
On top of optimizing an AST, this tool can now check whether both
ASTs match (or don't match) a specified packet, and fail if the
results disagree.
> Added a feature to check opt/unopt packet matches

- src/pf/parse.lua
https://github.com/Igalia/pflua/issues/139
Results no longer diverge in property-based testing, specialized to packet access;
this was thousands of test cases.
> Fixed bug 139, broken multi-octet access

- src/pf/parse.lua
https://github.com/Igalia/pflua/issues/137
(Keyword elision not implemented: sctp)
https://github.com/Igalia/pflua/issues/133
(len == 4 doesn't parse)
> Added lightweight parsing regression tests

- doc/Makefile
- doc/packet-access-igmp.md
- doc/packet-access-igrp.md
- doc/packet-access-pim.md
- doc/packet-access-sctp.md
- doc/packet-access-vrrp.md
- src/pf/expand.lua
- src/pf/parse.lua
A filter of "igmp" compiles with pflua, but not a filter of "igmp[8] < 7" or anything else using the [] syntax, unlike tcpdump.
```
% ./pflua-match ../tests/data/wingolog.pcap "igmp"   
Matched 0/19589 packets in 7934 iterations: ../tests/data/wingolog.pcap (155.411511 MPPS).
```
```
% ./pflua-match ../tests/data/wingolog.pcap "igmp[8] < 7"
luajit: ../src/pf/parse.lua:290: 
Error: In expression "igmp[8] < 7"
^
keyword elision not implemented [
stack traceback:
[C]: in function 'primitive_error'
../src/pf/parse.lua:290: in function 'error'
../src/pf/parse.lua:838: in function 'parse_primitive_or_arithmetic'
../src/pf/parse.lua:859: in function 'parse_logical_or_arithmetic'
../src/pf/parse.lua:891: in function 'parse_logical'
../src/pf/parse.lua:884: in function …
```
> Keyword elision not implemented with packet access: igmp, pim, igrp, vrrp

- .gitmodules
Reduce the load that our continuous-integration system puts on luajit.org.
> Use Snabb's GitHub mirror of the LuaJIT repository

- src/pf/utils.lua
- tests/Makefile
See https://github.com/Igalia/pflua/issues/148
A lightweight regression test has been added to the Makefile.
> Print empty arrays/tables, so PF_VERBOSE does not cause crashes.

- src/pf/utils.lua
This is to make it possible to use pflua and ljsyscall at the same
time. Both libraries define 'struct timeval' and this creates a
conflict because LuaJIT FFI wants both definitions in the same scope.
I am not sure if this is the best way to resolve the conflict. I don't
know of any LuaJIT convention along the lines of:
#ifndef TIME_H
#define TIME_H
...
#endif
I suppose that the LuaJIT ecosystem may be small enough that conflicts
can be dealt with as they arise, as in this commit.
> pf.utils: Rename FFI struct 'timeval' to 'pflua_timeval'

- Makefile
- common.mk
- doc/Makefile
- src/Makefile
- tests/Makefile
- tools/Makefile
Pflua uses recursive make, without autotools.
This change adds a $ABS_TOP_SRCDIR variable, inspired by autoconf,
to make the way the Makefiles deal with paths be less fragile.
Note that this intentionally means that only the top-level Makefile should
be invoked by hand; the rest now depend on it. For now, this can be worked
around by setting ABS_TOP_SRCDIR appropriately while invoking the dependent
Makefiles, but this is not advised.
> Refactor Makefile path handling

- src/pf/parse.lua
As raised in https://github.com/Igalia/pflua/issues/153
This change introduces a clearer and much more verbose error message on
similar invalid pflang input.
> Better errors on unknown possible-keywords

- Makefile
It was previously unset, which was a latent bug.
> Set TOP_SRCDIR in the root Makefile

- tests/Makefile
- tests/pflang-reg/pl-bug132-icmp6_or_ip
- tests/pflang-reg/pl-bug132-icmp6_or_portrange
- tests/pflang-reg/pl-bug132-not_icmp6
Regression tests for bug 132.
https://github.com/Igalia/pflua/issues/132
pure-lua 'icmp6 or (expr)' and "not icmp6" broken
> Added pflang-level regression tests for bug 132

- src/pf/optimize.lua
* src/pf/optimize.lua (lhoist): Fix typo extracting length ranges from
the annotated test of an if.  Fix typo computing length ranges for the
result of an if.
> Fix length-check hoisting bug

- tests/Makefile
- tests/properties/pipecmp_proto_or_proto.lua
The purpose of this test is to decrease the odds of missing any further
bugs which appear in expressions like "icmp or arp".
> Added a property-based test for 'proto or proto'

- doc/dst-portrange-80-90.md
- doc/portrange-0-6000.md
- doc/proto-47.md
- src/pf/expand.lua
* src/pf/expand.lua (expand_atalk, expand_aarp, expand_ipx)
(expand_decnet_src, expand_decnet_dst, expand_isis_protocol): Use
'false' as the failure continuation, not 'fail'.
(expand_offset): Use 'false' as the failure continuation when checking
that a packet is of a certain protocol.  Fixes #171.
We seem to uncover some CSE failures though :(
> Packet access doesn't abort if the packet is of the wrong type

- doc/dst-host-192.68.1.1-and-greater-100.md
- doc/dst-portrange-80-90.md
- doc/portrange-0-6000.md
- doc/src-host-192.68.1.1-and-less-100.md
- src/pf/anf.lua
- src/pf/optimize.lua
- src/pf/ssa.lua
* src/pf/optimize.lua (simple): Add an operator 'match', for 'true' in
tail position.
(simplify): Always lower 'false' in tail position to 'fail', and lower
'true' to 'match'.  That way we won't need to eta() to identify
accept/reject continuations of an "if"'s test -- we just look at the
consequent expressions.
(infer_ranges, lhoist): Lose the eta conversion.
(optimize_inner): Pass the initial "is-tail=true" flag to simplify.
(selftest): Adjust expectations.
* src/pf/anf.lua:
* src/pf/ssa.lua: Handle 'match'.
* doc/dst-host-192.68.1.1-and-greater-100.md:
* doc/src-host-192.68.1.1-and-less-100.md: Regenerate.
> Represent tail continuations in optimize IR

- tests/pflang-reg/pl-bug129-flipportrange.sh
https://github.com/Igalia/pflua/issues/129
BPF and pure-lua pipelines used to diverge on portrange N-M, M<N
> Regression test for bug 129, flipped portranges

- doc/dst-host-192.68.1.1-and-greater-100.md
- src/pf/optimize.lua
* src/pf/optimize.lua (lhoist): In tail position, only the minimum
packet length for the expression to be true is important.
(selftest): Add a test.
* doc/dst-host-192.68.1.1-and-greater-100.md: Regenerate.
Fixes #189.
> lhoist lifts more length checks in tail position

- src/pf/parse.lua
Hello! This patch makes IPv6 parsing follow [specification](https://tools.ietf.org/html/rfc4291#section-2.2) more closely: IPv4 representation of lowest 32 bits is now accepted, and more invalid addresses are rejected. For examples see added tests.
> IPv6: accept dotted quad suffix

- src/pf/parse.lua
* Fix `not` operator precedence: it should be higher than `and` and `or`.
* Accept `!` as an alternate form (expander handles it already).
> Fix 'not' operator precedence and alternate form

- tests/pflang-reg/pl-bug-171-arpind_or_tcp
https://github.com/Igalia/pflua/issues/171
(Packet indexing should cause conditions and assertions)
This also serves as a regression test for bug 166.
https://github.com/Igalia/pflua/issues/166
(More 'or' cases broken with packet indexing)
> Added a regression test for bug 171

- tests/pflang-reg/pl-bug130-allreject
https://github.com/Igalia/pflua/issues/130
Note that this is a workaround that makes pflua's libpcap pipeline
behave like the other pipelines, rather than failing fast like
libpcap does.
> Added a regression test for bug 130, libpcap failfast

- src/pf/optimize.lua
- tests/pflang-reg/pl-bug205-greater1_or_less1
'min' is a lower bound, not a precisely-known value; treat it accordingly.
This resolves https://github.com/Igalia/pflua/issues/205
> Reduce >= less aggressively

- tools/pflua-pipelines-match
'Match' is overloaded in this context.
> Reworded pflua-pipeline-match to say 'concur'

- tests/Makefile
- tests/pfquickcheck/pflang.lua
- tests/properties/pflua_pipelines_match.lua
This is a WIP, but it's in a state where it's already useful. It has two parts:
a) pflang.lua generates a subset of pflang
b) pflua_pipelines_match.lua compares the results of expressions generated with a) on a random packet, after compiling with the pure-lua and bpf-lua pipelines.
> Generate pflang and test pure-lua vs bpf-lua pipelines.

- src/pf/optimize.lua
Remove unnecessary allocations in cfkey calculation. On my machine compiling the 8k pflang from #216 becomes 30% faster (2 seconds -> 1.3 seconds), and total allocated memory goes down by 60% (1100 Mbytes -> 300 Mbytes).
> Improve optimizer performance

- tools/pflua-expand
Fix flag for disabling optimization (-O0) in pflua-expand tool to work in the same way as in pflua-compile tool.
> Fix -O0 flag for pflua-expand tool

- src/pf/libpcap.lua
It's being lazily loaded, and some functions previously could fail because it
was 'nil' when they were called. Always check it's loaded before using it.
> Make sure the pcap library is loaded

- src/pf/optimize.lua
Originally this patch was an attempt to fix #225, but it happened to be unrelated (see #225 for details). The patch is kept as a cleanup.
> Cleanup of function passed to 'memoize'

- src/pf/parse.lua
Starting with low-hanging fruit from #213.
tcpdump rejects 'portrange 0x1-0x2'. Use lexer's function for parsing
decimal literals when dealing with portrange parts instead of tonumber,
as it accepts hexadecimal literals even when base 10 is passed.
> Reject hexadecimal port numbers in portrange

- src/pf/parse.lua
Since there is no port/address ambiguity anymore, when looking for an
address bare numbers can always be interpreted as IPv4 addresses with
one field. Therefore, special function for parsing IPv4 as 'net' argument
can be removed.
Fixes issue: bare numbers as 'net' arguments were not interpreted
correctly if there was more than one space after 'net'.
Fixes issue: hostnames starting with a number looking like a part
of IPv4 were not interpreted correctly.
Added parser tests for fixed issues.
> Remove duplicated IPv4 parsing

- doc/Makefile
- doc/extensions.md
- doc/pflang.md
- doc/tcp-address.md
- src/pf/expand.lua
- src/pf/parse.lua
- tools/dump-markdown
* doc/Makefile (tcp-address.md):
* doc/tcp-address.md: New file.
* doc/pflang.md: Link to extensions.md.  Fix description of what happens
on ip[0] for a non-IP packet.
* src/pf/parse.lua (allow_address_of): New exported flag, on by
default.
(parse_addressable, parse_primary_arithmetic): Add addressable
parsing.
* tools/dump-markdown: Allow libpcap compilation to fail.
> Add address-of pflang extension

- src/pf/optimize.lua
`if A fail fail` can appear when some checks are conflicting, e.g. `tcp and tcp[100] == 1` used to compile to
```lua
local lshift = require("bit").lshift
local band = require("bit").band
local cast = require("ffi").cast
return function(P,length)
if length < 14 then return false end
local var1 = cast("uint16_t*", P+12)[0]
if var1 == 8 then
if length < 54 then return false end
if P[23] ~= 6 then return false end
if band(cast("uint16_t*", P+20)[0],65311) ~= 0 then return false end
local var7 = lshift(band(P[14],15),2)
if (var7 + 115) > length then return false end
return P[(var7 + 114)] == 1
else
if var1 ~= 56710 then return false end
if length < 54 then return false end
local var15 = P[20]
return false
end
end
```
Note the path that always returns false. With this change it compiles to …
> Simplify 'if A fail fail' to 'fail'

- doc/decnet-host-10.15.md
- doc/decnet-src-10.15.md
- doc/dst-host-192.68.1.1-and-greater-100.md
- doc/dst-portrange-80-90.md
- doc/fail-fail.md
- doc/host-127.0.0.1.md
- doc/icmp-or-tcp-or-udp.md
- doc/icmp6-or-ip.md
- doc/icmp6.md
- doc/ip6-proto-47.md
- doc/ip6-proto-ah.md
- doc/l1.md
- doc/net-127.0.0.0-8.md
- doc/packet-access-igmp.md
- doc/packet-access-igrp.md
- doc/packet-access-pim.md
- doc/packet-access-sctp.md
- doc/packet-access-vrrp.md
- doc/portrange-0-6000.md
- doc/proto-47.md
- doc/sctp.md
- doc/src-host-192.68.1.1-and-less-100.md
- doc/src-port-80.md
- doc/tcp-address.md
- doc/tcp-port-80.md
- src/pf/anf.lua
* src/pf/anf.lua: Renumber vars before lowering to CPS, for better
readability.
This one probably conflicts with "optimize pfmatch".  I can regenerate the .md files when that lands, or vice versa.
> Renumber ANF-generated vars for readability

- tests/Makefile
With parallel builds enabled (e.g. via `make -j 4 check` or
MAKEFLAGS set to '-j 4'), the "tests" makefile schedules the download of
data/wingolog.pcap in parallel with the tests that depend on that file
(issue #244). This commit restricts the parallelism in tests/Makefile to
prevent this.
The following targets in tests/Makefile depend on data/wingolog.pcap:
* check (via quickcheck, regression and its own rule)
* quickcheck (via its own rules)
* regression (via pflang_regression_tests and ir_regression_tests)
* ir_regression_tests (via $IR_REGRESSION_TESTS)
* pflang_regression_tests (via $PFLANG_REGRESSION_TESTS)
With parallel builds enabled, prior to this commit `make $TARGET` with
$TARGET set to any of the targets listed above is likely to fail if
data/wingolog.pcap has not been …
> tests/Makefile: finish download before running tests (fixes #244)

- src/pf/expand.lua
- src/pf/parse.lua
Equivalent to `src host <address>` and `dst host <address>`. Fixes #248.
> Support `src <address>` and `dst <address>`

- src/pf/backend.lua
- src/pf/match.lua
- tools/pflua-compile
Adds some more unit tests for pfmatch that execute filters (it hardcodes a path to the data directory for the tests, is that ok?) and should fix issue #252. Also includes a minor fix to the usage printout for `pflua-compile`.
> Add more tests and fix issue #252

- src/pf/backend.lua
- src/pf/match.lua
This fixes a potential pfmatch design issue I mentioned briefly to @wingo in St. Louis. When you compile a pfmatch expression like this:
```
$ ../tools/pflua-compile --match "match { ip => handler }"
local cast = require("ffi").cast
return function(self,P,length)
if length < 14 then return false end
if cast("uint16_t*", P+12)[0] == 8 then return self.handler(P, length) end
return false
end
```
The resulting handler call looks like `self.handler(P, length)` which doesn't pass the `self` parameter along. Compiling the call to `self:handler(P, length)` would probably be more useful so that you can pass state to the handler methods.
(note: this PR depends on PR #253 --- only commit a3cff6f is new to this branch)
> Use method invocation for pfmatch handler calls

- src/pf/bpf.lua
This is a fix for #185. The bug is triggered by any multiplication with variable operand (without optimizations BPF moves constants a lot so they look like variables), e.g. `ip[0] * ip[1] = 4`. A regression test is still needed.
> Fix error in BPF pipeline triggered by multiplication

- src/pf.lua
Adds @mpeterv test case as regression test for #250.
The test case crashed BPF compilation pipeline before #250 fix.
```
luajit: ./pf/bpf.lua:65: attempt to compare string with number
stack traceback:
./pf/bpf.lua:65: in function 'runtime_u32'
./pf/bpf.lua:98: in function 'is_power_of_2'
./pf/bpf.lua:253: in function 'alu'
./pf/bpf.lua:327: in function 'compile_lua'
./pf/bpf.lua:444: in function 'compile_filter'
./pf.lua:92: in function 'test_attempt_to_compare_string_with_a_number'
./pf.lua:94: in function 'selftest'
(command line):1: in main chunk
[C]: at 0x004043b0
```
> Add regression test for PR#250

- doc/Makefile
- doc/proto-sctp.md
- src/pf/expand.lua
It looks like at some point the `proto` operation broke in pflua. I've added some tests for it and added a fix.
This also updates the `proto \sctp` example. I was less sure about this part so please let me know if I didn't do the update quite right.
Related to issue #255
> Fix 'proto' operation
