- src/pf/parse.lua
There was an use case that was not working correctly (3ffe:500::/28).
src/pf/parse.lua: Refactored IPv6 parsing code.
> Fix IPv6 address parsing

- src/pf/quickcheck.lua
- tests/pfquickcheck/pflua-quickcheck
* src/pf/quickcheck.lua: New file.
* tests/pfquickcheck/pflua-quickcheck: Use the new module.
> Pull guts of pflua-quickcheck out to a module.

- doc/Makefile
- doc/decnet-host-10.15.md
- doc/decnet-src-10.15.md
- doc/dst-portrange-80-90.md
- doc/ether-broadcast.md
- doc/ether-multicast.md
- doc/ether-proto-1500.md
- doc/ether-proto-1501.md
- doc/ether-proto-255.md
- doc/ether-proto-decnet.md
- doc/icmp6.md
- doc/ip-multicast.md
- doc/ip-proto-47.md
- doc/ip-proto-ah.md
- doc/ip-proto-sctp.md
- doc/ip6-multicast.md
- doc/ip6-proto-47.md
- doc/ip6-proto-ah.md
- doc/iso-proto-47.md
- doc/iso-proto-clnp.md
- doc/l1.md
- doc/proto-47.md
- doc/src-port-80.md
* doc/Makefile: Add pflua deps for all filters so that they
automatically regenerate.  Regenerate them.
> Regenerate filters

- src/pf/optimize.lua
* src/pf/optimize.lua: Keep objects in the cache alive.  Before, this
wasn't happening because the objects were being stringified to be made
as keys to the cache.  This bug could cause spurious cache hits, if a
cached arg was collected and a new table was allocated at the same
memory address.
> Fix memoization bug

- src/pf/optimize.lua
* src/pf/optimize.lua: Instead of using Inf as "maximum" bounds, more
closely model the possible ranges of numbers, given that we have fixed
the 64-bit multiplication bug.  Also add assertions that bounds are
not NaN.
> Fix range inference bugs with division and other ops

- src/pf/optimize.lua
* src/pf/optimize.lua (try_invert): We can "invert" a ntohl because its
argument, result, and the comparison are in the same group.  This is
not the case for "ntohs" because it truncates the incoming 32-bit
value; you end up optimizing ntohs(uint32(x))==0 to uint32(x)==ntohs(0),
which is not right.  Yet, inversion of ntohs is needed.  So now we go
to the effort to preserve the truncating aspect of ntohs, and only
invert in those situations.
> Fix "inversion" optimization for ntohs

- src/pf/parse.lua
https://github.com/Igalia/pflua/issues/129
> Fix bug 129, bpf and pure-lua pipelines diverge on portrange N-M, M<N

- doc/Makefile
- doc/sctp.md
- src/pf/expand.lua
- src/pf/parse.lua
> Implement operator 'sctp'

- src/pf/expand.lua
> Fix net expand

- src/Makefile
https://github.com/Igalia/pflua/issues/155
> Removed vestigial Makefile targets

- doc/Makefile
- doc/icmp6-or-ip.md
- src/pf/expand.lua
- src/pf/parse.lua
> Make has_ipv6_protocol check packet is ipv6

- tools/pipe-lua-libpcap-match
- tools/pipe-unopt-opt-match
Tools to check whether pipelines match:
pure-lua vs bpf-lua vs pure-libpcap
pure-lua, optimized vs unoptimized
> Pipelinematch

- tools/pflua-expand
Use and intent are similar to pflua-compile.
> Added a tool to expand pflang to pflua IR

- src/pf/parse.lua
> IPv4: accept dotted triples, dotted pairs, and bare numbers

- src/pf/expand.lua
> Replace constant numbers for constant literals

- tests/pflang-reg/pl-bug182-icmp_or_arp
Top-level bug report for the root cause (length hoisting):
https://github.com/Igalia/pflua/issues/182
Original report:
https://github.com/Igalia/pflua/issues/178
Investigation:
https://github.com/Igalia/pflua/issues/180
Fix:
https://github.com/Igalia/pflua/pull/181
> Regression test for bug182 length hoisting

- doc/dst-host-192.68.1.1-and-greater-100.md
- doc/icmp-or-tcp-or-udp.md
- doc/icmp6-or-ip.md
https://github.com/Igalia/pflua/issues/182
> Changes from the length-hoisting fix

- src/pf/expand.lua
* src/pf/expand.lua (expand_offset, expand_arith, expand_relop)
(expand_bool): Instead of collecting assertions in a list and then
asserting each one, we have the assertions carry their continuations
also.  This is a no-op change but is a precursor to fixing #171.
> Guard expressions specify their failure continuation

- tests/pflang-reg/pl-bug139-multioctet.sh
https://github.com/Igalia/pflua/issues/139
> Added a regression test for bug 139, multi-octet packet access

- tests/pflang-reg/pl-bug131-notlen-igrp
- tests/pflang-reg/pl-bug131-notlen-rarp
- tests/pflang-reg/pl-bug131-notlen-tcpport
https://github.com/Igalia/pflua/issues/131
> Added regression tests for 131, 'not' broken

- src/pf/parse.lua
A tiny fix: due to a wrong variable name parser error included `nil` instead of actual token on invalid portrange.
> Fix error message when parsing invalid portrange

- src/pf/backend.lua
> Fix backend quadratic performance

- src/pf/parse.lua
This is https://github.com/mpeterv/pflua/commit/3375a413d025b1970adb7bb7034df73f94aa1c6e and https://github.com/mpeterv/pflua/commit/1394b279480f507489df0d081aa28ea7fc7793ee, plus a fixup to make a lexer test less strange.
> Context sensitive lexing

- src/pf/optimize.lua
This change allows associative binop folding to always work if an expression tree contains at least two numbers. E.g. `(A + C1) + (B + C2)` now folds to `(A + B) + (C1 + C2)`.
This improves code generated for #215: 517 lines -> 472 lines, 270 arithmetic ops (number of pluses) -> 187 ops.
```lua
local lshift = require("bit").lshift
local band = require("bit").band
local cast = require("ffi").cast
return function(P,length)
if length < 14 then return false end
local var1 = cast("uint16_t*", P+12)[0]
if var1 == 8 then
if length < 54 then return false end
if P[23] ~= 6 then return false end
if band(cast("uint16_t*", P+20)[0],65311) ~= 0 then return false end
local var7 = lshift(band(P[14],15),2)
if (var7 + 28) > length then return false end
if band(P[(var7 + 27)],2) == 0 then return false end …
```
> Fold associative binops more aggresively

- doc/extensions.md
- doc/pfmatch.md
- src/Makefile
- src/pf/anf.lua
- src/pf/backend.lua
- src/pf/match.lua
- src/pf/optimize.lua
- src/pf/parse.lua
- src/pf/ssa.lua
See #229.
* src/pf/parse.lua: Add options dict, and ability to parse arithmetic
expressions directly.
* src/pf/dispatch.lua: New file.
* src/Makefile: Add new file.
> Add parser for dispatch language

- src/pf/parse.lua
Use same function for parsing numerical literals in arithmetic
expressions and as arguments of primitives, e.g. 'port'. Add some
error reporting to this function; previously lexer had to fallback
to address parsing on incorrect number literals.
This improves tcpdump compatibility.
> Allow octal literals as arguments

- doc/icmp-or-tcp-or-udp.md
- doc/icmp6-or-ip.md
- doc/pfmatch.md
- doc/src-host-192.68.1.1-and-less-100.md
- src/pf/backend.lua
- src/pf/optimize.lua
- tools/pflua-compile
> Optimize pfmatch

- src/pf/anf.lua
- src/pf/backend.lua
Fixes issue #259. Also added an assert that will catch the bug in tests.
> Fix issue #259
